# Configuration for the API Comparison Tool

# Set the type of test to run: "REST" or "SOAP"
testType:  "REST" #"SOAP" #"REST" # 

# Configuration block for REST APIs
rest:
  api1:
    url: "http://localhost:8081/api/resource"
    method: "POST"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    authentication:
      tokenUrl: null
      clientId: null
      clientSecret: null
    payloadTemplatePath: "C:\\muleguard-fixed\\tmp\\in\\api1\\payload.json"
  api2:
    url: "http://localhost:8082/api/resource"
    method: "POST"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    authentication:
      tokenUrl: null
      clientId: null
      clientSecret: null
    payloadTemplatePath: "C:\\muleguard-fixed\\tmp\\in\\api2\\payload.json"

# Configuration block for SOAP APIs
soap:
  api1:
    url: "http://localhost:8083/ws/AccountService" #"http://localhost:9090/Service/orderService.serviceagent/createOrderEndpoint1"  #"http://localhost:8083/ws/AccountService"
    method: "POST"
    headers:
      Content-Type: "text/xml;charset=UTF-8"
      SOAPAction: "getAccountDetails" #"/Service/orderService.serviceagent/createOrderEndpoint1/Operation"  #"getAccountDetails"
    authentication:
      tokenUrl: null
      clientId: null
      clientSecret: null
    #payloadTemplatePath: "/Users/raks/Library/CloudStorage/OneDrive-IBM/Documents/GitHub/t2mtools/muleguard_runtimeupgrade/apiurlcomparison/sample/in/api1/payload.xml"
    payloadTemplatePath: "C:\\muleguard-fixed\\tmp\\in\\api1\\payload.xml"
  api2:
    url: "http://localhost:8084/ws/AccountService"
    method: "POST"
    headers:
      Content-Type: "text/xml;charset=UTF-8"
      SOAPAction: "getAccountDetails"
    authentication:
      tokenUrl: null
      clientId: null
      clientSecret: null
    #payloadTemplatePath: "/Users/raks/Library/CloudStorage/OneDrive-IBM/Documents/GitHub/t2mtools/muleguard_runtimeupgrade/apiurlcomparison/sample/in/api2/payload.xml"
    payloadTemplatePath: "C:\\muleguard-fixed\\tmp\\in\\api2\\payload.xml"

# Set the maximum number of iterations to run, as a safeguard.
maxIterations: 1000

# Define tokens and the values to iterate over.
# The tool will generate iterations from all possible combinations (Cartesian product) of the token values provided below.
tokens:
  account:
    - "12345"
    - "999"
    - "0"
    - -123456
    - ""
  uuid:
    - "a1b2c3d4-e5f6-7890-1234-567890abcdef"
    - "f0e9d8c7-b6a5-4321-fedc-ba0987654321"
  param:
    - "True"
    - "False"
